apiVersion: v1
kind: Service
metadata:
  name: ftps-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: sharedip
spec:
  selector:
    app: ftps
  type: LoadBalancer
  ports:
    - protocol: TCP
      name: ftps
      port: 21
      targetPort: 21
    - protocol: TCP
      name: ftps-passive
      port: 1500
      targetPort: 1500
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
spec:
  selector:
    matchLabels:
      app: ftps
  replicas: 1
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps_image
        imagePullPolicy: Never
        ports:
        - containerPort: 21
        - containerPort: 1500