apiVersion: v1
kind: Service
metadata:
  name: php-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: sharedip
spec:
  selector:
    app: php
  type: LoadBalancer
  ports:
    - protocol: TCP
      name: php
      port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  # labels:
  #   test: liveness
  name: php-deployment
spec:
  selector:
    matchLabels:
      app: php
  replicas: 1
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
      - name: php
        image: php_image
        imagePullPolicy: Never
        ports:
        - containerPort: 5000