apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: sharedip
spec:
  selector:
    app: nginx
  type: LoadBalancer
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
    - protocol: TCP
      name: https
      port: 443
      targetPort: 443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  # labels:
  #   test: liveness
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx_image
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        - containerPort: 443
        # - containerPort: 20
        # livenessProbe:
        #   exec:
        #     command:
        #     - ret=$(ps aux | grep [s]shd | wc -l); touch /tmp/$ret ; cat /tmp/1 ; rm -rf /tmp/1
        #   initialDelaySeconds: 10
        #   periodSeconds: 10